### ISSUE TITLE
Progress now stopping at 100% - Drop not completing/claimed

### ISSUE THREAD

**Issue by dogodogowoof** [Windows200000/TwitchDropsMiner-updated#95] opened 2024-06-05 03:50 UTC
Similar to what happened prior, where progress stops at 100% (or near when looking at Twitch). 

v15.5.0 (0f42b24)

**Comment by Windows200000** [comment] 2024-06-05 15:25
duplicate of #85

**Closed by Windows200000** 2024-06-05 15:25 UTC
Labels: Duplicate
