### ISSUE TITLE
Fatal Error when completing a Twitch Drop + Error: Exception in task

### ISSUE THREAD

**Issue by flamedance58** [Windows200000/TwitchDropsMiner-updated#96] opened 2024-06-05 08:58 UTC
01:51:09: Fatal error encountered:
01:51:09: 
01:51:09: Traceback (most recent call last):
01:51:09:   File "main.py", line 158, in main
01:51:09:   File "twitch.py", line 772, in run
01:51:09:   File "twitch.py", line 828, in _run
01:51:09:   File "inventory.py", line 232, in claim
01:51:09:   File "inventory.py", line 138, in claim
01:51:09:   File "inventory.py", line 154, in _claim
01:51:09:   File "twitch.py", line 1574, in gql_request
01:51:09: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
01:51:09: 
01:51:09: Exiting...
01:51:10: 
01:51:10: Application Terminated.
01:51:10: Close the window to exit the application.

I recently started getting this with pretty much any Twitch Drop I set the app on.
Restarting the app does fix it but every time it completes a single item from a Twitch Drop it'll die, restart, finish another item, die, etc.

[Edit] After watching the app work through some more Twitch Drops it's not "everytime" seems to be random now.

**Comment by Windows200000** [comment] 2024-06-05 15:24
Duplicate of #86

**Closed by Windows200000** 2024-06-05 15:24 UTC
Labels: Duplicate
